name: Sean Joyal
description: The personal website of Sean Joyal, including projects, blog posts, and information about my journey in Front End Development.

paginate: 10

markdown: kramdown
permalink: /:title
